### ISSUE TITLE
Can you share your data?

### ISSUE THREAD

**Issue by chengjianhong** [Youngluc/CTFL-Beta#1]
I run the main.py. it notes the following error. I think that there are missing files. Can you make it available? Thanks.

```
D:\anaconda3\envs\py38-torch\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.  warnings.warn(msg)
Traceback (most recent call last):
  File "d:/workspace/CTFL-Beta/main.py", line 137, in <module>    main(args)
  File "d:/workspace/CTFL-Beta/main.py", line 118, in main
    data = MyDataset("./material")
  File "d:\workspace\CTFL-Beta\dataset.py", line 14, in __init__
    fh = os.listdir(p_t1)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './material\\t1'
```

**Comment by Youngluc** [comment]
Thanks for your attention of our work. Partial data is simulated by MATLAB.
You can use MSST source code to generate data. If you have any questions,
you can chat with me by WeChat(My wechat number: haochworktimes)! My raw
data is not of integrity.

Jianhong Cheng ***@***.***> 于2023年4月3日周一 18:19写道：

**Comment by chengjianhong** [comment]
@Youngluc Thanks, I try to add your WeChat, but it can't be searchable due to privacy settings.

**Comment by Youngluc** [comment]
Sorry, you can search by phone number(13293535011)

Jianhong Cheng ***@***.***> 于2023年4月4日周二 13:45写道：
